# Generated by Django 2.1.3 on 2019-04-26 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField(default=datetime.datetime(2019, 4, 26, 9, 6, 15, 892424, tzinfo=utc))),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
