# Generated by Django 2.1.3 on 2019-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(default='11-04-19')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
