# Generated by Django 2.1.3 on 2019-04-26 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 9, 9, 59, 107188, tzinfo=utc)),
        ),
    ]
