# Generated by Django 2.1.3 on 2019-04-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='name',
            new_name='title',
        ),
    ]
