# Generated by Django 2.1.3 on 2019-04-26 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190426_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 11, 0, 29, 399131, tzinfo=utc)),
        ),
    ]
