# Generated by Django 2.0 on 2019-07-05 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190426_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 7, 13, 17, 793650, tzinfo=utc)),
        ),
    ]
