# Generated by Django 2.0 on 2019-07-05 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190705_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 10, 39, 35, 328215, tzinfo=utc)),
        ),
    ]
