# Generated by Django 2.1.3 on 2019-04-12 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190412_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 9, 30, 49, 925818)),
        ),
    ]
