# Generated by Django 2.1.3 on 2019-04-12 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20190412_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 9, 33, 16, 681591)),
        ),
    ]
