# Generated by Django 2.0 on 2019-08-19 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_auto_20190819_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 7, 0, 56, 740670, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(),
        ),
    ]
